#!/usr/bin/env node
import { createHash } from "node:crypto";
import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const appRoot = path.dirname(fileURLToPath(import.meta.url));
const sourceRoot = path.resolve(appRoot, "..", "design_planner");
const publicRoot = path.join(appRoot, "public");

await mkdir(publicRoot, { recursive: true });

const copies = [
  [path.join(sourceRoot, "design_audit.js"), path.join(publicRoot, "design_audit.js")],
  [path.join(sourceRoot, "claim_math.js"), path.join(publicRoot, "claim_math.js")],
  [path.join(sourceRoot, "data", "design_audit.schema.json"), path.join(publicRoot, "design_audit.schema.json")],
  [path.join(sourceRoot, "data", "design_audit_fixtures.json"), path.join(publicRoot, "design_audit_fixtures.json")],
  [path.join(sourceRoot, "data", "validation_registry.json"), path.join(publicRoot, "validation_registry.json")],
  [path.join(sourceRoot, "data", "inferential_target_registry.json"), path.join(publicRoot, "inferential_target_registry.json")],
  [path.join(sourceRoot, "data", "claim_math_fixtures.json"), path.join(publicRoot, "claim_math_fixtures.json")],
  [path.join(sourceRoot, "data", "reference_grids.json"), path.join(publicRoot, "reference_grids.json")],
  [path.join(sourceRoot, "data", "decision_rules.json"), path.join(publicRoot, "decision_rules.json")],
  [path.join(sourceRoot, "data", "golden_test_fixtures.json"), path.join(publicRoot, "golden_test_fixtures.json")]
];

for (const [source, target] of copies) await copyFile(source, target);

const fixtureText = await readFile(
  path.join(sourceRoot, "data", "design_audit_fixtures.json"),
  "utf8"
);
const registryText = await readFile(
  path.join(sourceRoot, "data", "validation_registry.json"),
  "utf8"
);
const targetRegistryText = await readFile(
  path.join(sourceRoot, "data", "inferential_target_registry.json"),
  "utf8"
);
const claimMathFixtureText = await readFile(
  path.join(sourceRoot, "data", "claim_math_fixtures.json"),
  "utf8"
);
const referenceGridText = await readFile(
  path.join(sourceRoot, "data", "reference_grids.json"),
  "utf8"
);
const decisionRulesText = await readFile(
  path.join(sourceRoot, "data", "decision_rules.json"),
  "utf8"
);
const goldenFixturesText = await readFile(
  path.join(sourceRoot, "data", "golden_test_fixtures.json"),
  "utf8"
);
const fixtureBundle = [
  "/* Generated by build.mjs from the shared audit artifacts. */",
  `window.DesignAuditFixtures = ${JSON.stringify(JSON.parse(fixtureText))};`,
  `window.DesignAuditRegistry = ${JSON.stringify(JSON.parse(registryText))};`,
  ""
].join("\n");
await writeFile(path.join(publicRoot, "audit_data.js"), fixtureBundle, "utf8");

const claimBundle = [
  "/* Generated by build.mjs from the shared claim-routing artifacts. */",
  `window.InferentialTargetRegistry = ${JSON.stringify(JSON.parse(targetRegistryText))};`,
  `window.ClaimMathFixtures = ${JSON.stringify(JSON.parse(claimMathFixtureText))};`,
  `window.ReferenceGridRegistry = ${JSON.stringify(JSON.parse(referenceGridText))};`,
  `window.DecisionRulesRegistry = ${JSON.stringify(JSON.parse(decisionRulesText))};`,
  `window.GoldenTestFixtures = ${JSON.stringify(JSON.parse(goldenFixturesText))};`,
  ""
].join("\n");
await writeFile(path.join(publicRoot, "claim_data.js"), claimBundle, "utf8");

const artifactNames = [
  "index.html",
  "styles.css",
  "app.js",
  "design_audit.js",
  "claim_math.js",
  "design_audit.schema.json",
  "design_audit_fixtures.json",
  "validation_registry.json",
  "inferential_target_registry.json",
  "claim_math_fixtures.json",
  "reference_grids.json",
  "decision_rules.json",
  "golden_test_fixtures.json",
  "audit_data.js",
  "claim_data.js"
];
const hashes = {};
for (const name of artifactNames) {
  const bytes = await readFile(path.join(publicRoot, name));
  hashes[name] = createHash("sha256").update(bytes).digest("hex");
}

// Tie the page to its matching CSS/scripts instead of reusing a cached older UI.
const indexPath = path.join(publicRoot, "index.html");
const versionedIndex = (await readFile(indexPath, "utf8")).replace(
  /((?:src|href)="\.\/)([^"?]+)(?:\?v=[a-f0-9]+)?"/g,
  (reference, prefix, name) => hashes[name]
    ? `${prefix}${name}?v=${hashes[name].slice(0, 12)}"` : reference
);
await writeFile(indexPath, versionedIndex, "utf8");
hashes["index.html"] = createHash("sha256").update(versionedIndex).digest("hex");

const metadata = {
  build_contract_version: "1.3.0",
  design_audit_schema_version: "1.0.0",
  claim_router_schema_version: JSON.parse(targetRegistryText).schema_version,
  claim_math_schema_version: JSON.parse(claimMathFixtureText).schema_version,
  reference_grid_schema_version: JSON.parse(referenceGridText).schema_version,
  decision_rules_schema_version: JSON.parse(decisionRulesText).schema_version,
  golden_fixtures_schema_version: JSON.parse(goldenFixturesText).schema_version,
  validation_registry_version: JSON.parse(registryText).registry_version,
  sha256: hashes
};
await writeFile(
  path.join(publicRoot, "build-meta.json"),
  `${JSON.stringify(metadata, null, 2)}\n`,
  "utf8"
);

console.log(`Built ${artifactNames.length} static assets with SHA-256 metadata.`);
