# Shared utilities for the L2 vocabulary reliability simulations.

ensure_output_dirs <- function(out_dir = "outputs") {
  dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)
  dir.create(file.path(out_dir, "figures"), showWarnings = FALSE, recursive = TRUE)
  dir.create(file.path(out_dir, "session_info"), showWarnings = FALSE, recursive = TRUE)
  dir.create(file.path(out_dir, "validation"), showWarnings = FALSE, recursive = TRUE)
  invisible(out_dir)
}

fmt <- function(x, digits = 3) {
  ifelse(is.na(x), "NA", formatC(x, digits = digits, format = "f"))
}

safe_q <- function(x, p) {
  x <- x[is.finite(x)]
  if (length(x) == 0) {
    return(NA_real_)
  }
  unname(stats::quantile(x, p, na.rm = TRUE))
}

md_table <- function(df) {
  table_lines <- utils::capture.output(
    utils::write.table(df, sep = " | ", row.names = FALSE, quote = FALSE)
  )
  header <- table_lines[1]
  divider <- paste(rep("---", ncol(df)), collapse = " | ")
  paste(c(header, divider, table_lines[-1]), collapse = "\n")
}

alpha_binary <- function(x) {
  x <- as.matrix(x)
  storage.mode(x) <- "numeric"
  k <- ncol(x)
  if (k < 2 || nrow(x) < 2) {
    return(tibble::tibble(
      alpha = NA_real_,
      total_var = NA_real_,
      zero_var_items = NA_integer_,
      item_total_na = NA_integer_,
      mean_score = mean(rowMeans(x), na.rm = TRUE)
    ))
  }

  item_vars <- apply(x, 2, stats::var, na.rm = TRUE)
  total_scores <- rowSums(x, na.rm = TRUE)
  total_var <- stats::var(total_scores, na.rm = TRUE)
  zero_var_items <- sum(is.na(item_vars) | item_vars < 1e-12)

  item_total <- vapply(seq_len(k), function(j) {
    item <- x[, j]
    rest <- rowSums(x[, -j, drop = FALSE], na.rm = TRUE)
    if (stats::var(item, na.rm = TRUE) < 1e-12 ||
        stats::var(rest, na.rm = TRUE) < 1e-12) {
      return(NA_real_)
    }
    suppressWarnings(stats::cor(item, rest, use = "pairwise.complete.obs"))
  }, numeric(1))

  alpha <- if (is.na(total_var) || total_var < 1e-12) {
    NA_real_
  } else {
    k / (k - 1) * (1 - sum(item_vars, na.rm = TRUE) / total_var)
  }

  tibble::tibble(
    alpha = alpha,
    total_var = total_var,
    zero_var_items = zero_var_items,
    item_total_na = sum(is.na(item_total)),
    mean_score = mean(rowMeans(x), na.rm = TRUE)
  )
}

alpha_numeric <- function(x, complete_rows = TRUE) {
  x <- as.matrix(x)
  storage.mode(x) <- "numeric"
  if (complete_rows) {
    x <- x[stats::complete.cases(x), , drop = FALSE]
  }

  if (ncol(x) < 2 || nrow(x) < 2) {
    return(tibble::tibble(
      alpha = NA_real_,
      total_var = NA_real_,
      zero_var_items = NA_integer_,
      mean_score = NA_real_,
      n_used = nrow(x)
    ))
  }

  item_vars <- apply(x, 2, stats::var, na.rm = !complete_rows)
  total_scores <- rowSums(x, na.rm = !complete_rows)
  total_var <- stats::var(total_scores, na.rm = !complete_rows)
  zero_var_items <- sum(is.na(item_vars) | item_vars < 1e-12)
  alpha <- if (is.na(total_var) || total_var < 1e-12) {
    NA_real_
  } else {
    ncol(x) / (ncol(x) - 1) * (1 - sum(item_vars, na.rm = TRUE) / total_var)
  }

  tibble::tibble(
    alpha = alpha,
    total_var = total_var,
    zero_var_items = zero_var_items,
    mean_score = mean(rowMeans(x, na.rm = !complete_rows), na.rm = TRUE),
    n_used = nrow(x)
  )
}

mcse_mean <- function(x) {
  x <- x[is.finite(x)]
  if (length(x) < 2) {
    return(NA_real_)
  }
  stats::sd(x) / sqrt(length(x))
}

mcse_median_approx <- function(x) {
  x <- x[is.finite(x)]
  if (length(x) < 2) {
    return(NA_real_)
  }
  1.253 * stats::sd(x) / sqrt(length(x))
}

mcse_proportion <- function(x) {
  x <- x[!is.na(x)]
  if (length(x) == 0) {
    return(NA_real_)
  }
  p <- mean(x)
  sqrt(p * (1 - p) / length(x))
}

write_session_info <- function(label, out_dir = "outputs") {
  ensure_output_dirs(out_dir)
  path <- file.path(out_dir, "session_info", paste0(label, ".txt"))
  sim_env <- Sys.getenv()
  sim_env <- sim_env[grepl("^SIM|^TRACK", names(sim_env))]

  lines <- utils::capture.output({
    cat("label:", label, "\n")
    cat("timestamp:", format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z"), "\n")
    # Record the working directory with the home directory generalized to "~"
    # so regenerated logs never embed an identifying local path (the review
    # package additionally redacts absolute paths at build time; this guard
    # covers logs regenerated by re-running validations after that build).
    wd <- normalizePath(getwd())
    home <- normalizePath(path.expand("~"))
    if (startsWith(wd, home)) wd <- paste0("~", substring(wd, nchar(home) + 1))
    cat("working_directory:", wd, "\n")
    cat("R:", R.version.string, "\n\n")
    cat("simulation_environment:\n")
    if (length(sim_env) == 0) {
      cat("(none)\n")
    } else {
      print(sort(sim_env))
    }
    cat("\n")
    print(utils::sessionInfo())
  })
  lines <- sub("[[:space:]]+$", "", lines)
  writeLines(lines, path, useBytes = TRUE)

  invisible(path)
}
